server:
  port: 9527
  
spring: 
  application:
    name: springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: springcloud-provider-dept  #过滤掉某个微服务
  prefix: /edwin  ##设置统一的前缀名称
  ignored-services: "*"   ##过滤所有的微服务名称
  routes: 
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
 
info:
  app.name: EdwinYu
  company.name: yulang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  